import Link from "next/link";
import { getAdminDashboardData } from "@/features/orders/admin/server";
import { formatTwd } from "@/lib/money";
import styles from "./admin.module.css";

export default async function AdminDashboard() {
  const data = await getAdminDashboardData();
  const metrics = data.metrics ?? { revenueToday: 0, orderCountToday: 0, pendingShipping: 0, averageOrderValue: 0 };
  return <><div className={styles.titleRow}><div><div className="eyebrow">Overview · Supabase</div><h1 className="serif">早安，今天也慢慢做好每一單。</h1></div><Link className="button button-primary" href="/admin/products/new">新增商品</Link></div>{data.error && <div className={styles.notice}>{data.error}</div>}<section className={styles.metrics}><div className={styles.metric}><span>今日營業額</span><strong>{formatTwd(metrics.revenueToday)}</strong></div><div className={styles.metric}><span>今日訂單</span><strong>{metrics.orderCountToday}</strong></div><div className={styles.metric}><span>待出貨</span><strong>{metrics.pendingShipping}</strong></div><div className={styles.metric}><span>平均客單價</span><strong>{formatTwd(metrics.averageOrderValue)}</strong></div></section><div className={styles.panelGrid}><section className={styles.panel}><h2>最近訂單</h2><table className={styles.table}><thead><tr><th>訂單</th><th>顧客</th><th>付款</th><th>履約</th><th>金額</th></tr></thead><tbody>{data.orders.map((order) => <tr key={order.id}><td>{order.orderNumber}</td><td>{order.customerName}</td><td><span className={`badge ${order.paymentStatus === "paid" ? "badge-stock" : "badge-preorder"}`}>{order.paymentStatus === "paid" ? "已付款" : order.paymentStatus}</span></td><td>{order.fulfillmentStatus}</td><td>{formatTwd(order.grandTotal)}</td></tr>)}</tbody></table>{!data.orders.length && <p className={styles.empty}>目前尚無訂單。</p>}</section><section className={styles.panel}><h2>低庫存</h2><div className={styles.alertList}>{data.lowStock.map((item) => <div className={styles.alert} key={item.label}><span>{item.label}</span><strong>{item.available}</strong></div>)}</div>{!data.lowStock.length && <p className={styles.empty}>目前沒有低庫存項目。</p>}</section></div></>;
}
