import Link from "next/link";
import { getAdminDashboardData } from "@/features/orders/admin/server";
import { fulfillmentStatusLabels, paymentStatusLabels } from "@/features/orders/order-status-labels";
import { formatTwd } from "@/lib/money";
import styles from "./admin.module.css";

export default async function AdminDashboard() {
  const data = await getAdminDashboardData();
  const metrics = data.metrics ?? { revenueToday: 0, revenueMonth: 0, orderCountToday: 0, pendingShipping: 0, averageOrderValue: 0 };
  const fulfillmentLabels: Record<string, string> = { ...fulfillmentStatusLabels };
  const trend = data.trend ?? [];
  const maxRevenue = Math.max(...trend.map((item) => item.revenue), 1);
  return <><div className={styles.titleRow}><div><div className="eyebrow">總覽・資料庫</div><h1 className="serif">早安，今天也慢慢做好每一單。</h1></div><Link className="button button-primary" href="/admin/products/new">新增商品</Link></div>{data.error && <div className={styles.notice}>{data.error}</div>}<section className={styles.metrics}><div className={styles.metric}><span>今日營業額</span><strong>{formatTwd(metrics.revenueToday)}</strong></div><div className={styles.metric}><span>本月營業額</span><strong>{formatTwd(metrics.revenueMonth)}</strong></div><div className={styles.metric}><span>今日訂單</span><strong>{metrics.orderCountToday}</strong></div><div className={styles.metric}><span>待出貨</span><strong>{metrics.pendingShipping}</strong></div><div className={styles.metric}><span>平均客單價</span><strong>{formatTwd(metrics.averageOrderValue)}</strong></div></section><div className={styles.dashboardGrid}><section className={styles.panel}><h2>近 14 天營業額</h2><div className={styles.trend}>{trend.map((day) => <div className={styles.trendItem} key={day.date} title={`${day.date}：${formatTwd(day.revenue)}／${day.orders} 筆`}><div className={styles.trendBar} style={{ height: `${Math.max(4, (day.revenue / maxRevenue) * 100)}%` }} /><small>{day.label}</small></div>)}</div>{!trend.some((item) => item.revenue > 0) && <p className={styles.empty}>目前尚無已付款營業額。</p>}</section><section className={styles.panel}><h2>熱門商品</h2>{data.topProducts?.length ? <div className={styles.compactList}>{data.topProducts.map((product) => <div className={styles.compactItem} key={product.name}><strong>{product.name}</strong><span>{product.quantity} 件／{formatTwd(product.revenue)}</span></div>)}</div> : <p className={styles.empty}>目前尚無銷售資料。</p>}</section></div><div className={styles.panelGrid}><section className={styles.panel}><h2>最近訂單</h2><table className={styles.table}><thead><tr><th>訂單</th><th>顧客</th><th>付款</th><th>履約</th><th>金額</th></tr></thead><tbody>{data.orders.map((order) => <tr key={order.id}><td>{order.orderNumber}</td><td>{order.customerName}</td><td><span className={`badge ${order.paymentStatus === "paid" ? "badge-stock" : "badge-preorder"}`}>{paymentStatusLabels[order.paymentStatus] ?? "狀態更新"}</span></td><td>{fulfillmentLabels[order.fulfillmentStatus] ?? "狀態更新"}</td><td>{formatTwd(order.grandTotal)}</td></tr>)}</tbody></table>{!data.orders.length && <p className={styles.empty}>目前尚無訂單。</p>}</section><section className={styles.panel}><h2>低庫存</h2><div className={styles.alertList}>{data.lowStock.map((item) => <div className={styles.alert} key={item.label}><span>{item.label}</span><strong>{item.available}</strong></div>)}</div></section></div></>;
}
